#!/bin/bash

solversFolder="../../../applications/solvers"
solver="laplacianFoam.py"

# Make mesh using following commands
#fe41
#blockMesh
#fluentMeshToFoam tri_coarse.msh#blockMesh
#fluentMeshToFoam tri_fine.msh

./Allclean

python3 $solversFolder/$solver
