#!/bin/bash

solversFolder="../../../applications/solvers"
solver="laplacianFoam.py"

./Allclean

#blockMesh
#fe41
#fluentMeshToFoam tri_coarse.msh
#fluentMeshToFoam tri_fine.msh 

python3 $solversFolder/$solver
