#!/bin/bash

solversFolder="../../../applications/solvers"
solver="laplacianFoam.py"

# Source OpenFOAM for mesh generation and postProcessing options
if [[ -z "${WM_PROJECT}" ]]
then
    # Check if OpenFOAM/FOAM has been sourced
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1
else
    allowed_ver=("v2012" "v2106" "v2112" "v2206" "v2212" "v2306" "v2312")
    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
        echo "Unsupported OpenFOAM version sourced!"
    fi
fi

# Check virtual environment version    
if [[ -z "$VIRTUAL_ENV" ]]; then
    echo "Error: No virtual environment is active!" >&2
    exit 1
elif [[ "$(basename "$VIRTUAL_ENV")" != "venv-HoPyFoam" ]]; then
    echo "Error: Wrong virtual environment is active!"
    echo "Expected: venv-HoPyFoam, but found: $(basename "$VIRTUAL_ENV")" >&2
    exit 1
fi

./Allclean

blockMesh > /dev/null 2>&1

# For tri mesh
#fluentMeshToFoam tri_coarse.msh#blockMesh
#fluentMeshToFoam tri_fine.msh

python3 $solversFolder/$solver
