name: Check Added Files Format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check_added_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Run the checkFileHeader script on added files
        run: |
          # Run script on each added file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do

            extension="${file##*.}"
            echo "Current directory: $(pwd)"
            ls
            ls applications/scripts/
            chmod +x ./applications/scripts/checkFileHeader.sh
            
            if [ "$extension" == "py" ]; then
              ./applications/scripts/checkFileHeader.sh "$file"
            fi
          done
